# For use with Github Actions to override plantuml execution.
---
INHERIT: mkdocs_local.yml

markdown_extensions:
  - footnotes
  - nl2br
  - attr_list
  - md_in_html
  - meta
  - smarty
  - tables
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: True
  - mdx_breakless_lists
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tasklist:
       custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - plantuml_markdown:
      format: png
      base_dir: !relative
#      server: 'https://plantuml.com/plantuml'
#      server: ''
#      kroki_server: ''
      plantuml_cmd: 'java -DPLANTUML_SECURITY_PROFILE=UNSECURE -DPLANTUML_LIMIT_SIZE=8192 -Dplantuml.include.path="docs/Projects:docs/assets/plantuml:docs" -Djava.awt.headless=true -jar plantuml.jar -config docs/assets/plantuml/config.cfg'

plugins:
  - search
  - awesome-pages
  - macros
  - meta-descriptions
  - ezlinks:
      wikilinks: true
  - callouts
  - glightbox:
      auto_caption: true

extra_javascript:
   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
    - assets/css/admonition.css
    - assets/css/custom_attributes.css
    - assets/css/customization.css
    - assets/css/draft-watermark.css

extra:
  draftMark: |
    &nbsp;
    { .draftWatermark }
  generator: false
  SEO: assets/meta/SEO.png
  comments: false #disable comments globally
  generate_graph: true #generate the graph of the site
  attachments: 'assets/img' #path to the folder where the attachments are stored
  no-auto-h1: false #disable the automatic generation of h1 if no h1 is found
  hooks:
    strip_comments: true
    fix_heading: true